ALTER TABLE players ADD COLUMN IF NOT EXISTS citizenid VARCHAR(20) UNIQUE;

CREATE TABLE IF NOT EXISTS cid_registry (
  id INT AUTO_INCREMENT PRIMARY KEY,
  license VARCHAR(60) NOT NULL,
  citizenid VARCHAR(20) NOT NULL UNIQUE,
  slot INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_license (license),
  INDEX idx_citizenid (citizenid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS id_card_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  citizenid VARCHAR(20) NOT NULL,
  action VARCHAR(50) NOT NULL,
  data JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
