Config = Config or {}

Config.ServerGuide = {
    command = 'rules',
    title = 'Server Guide',
    tabs = { 'Server Rules', 'Key Binds', 'Staff Contacts' },
    rules = {
        { title = '1. Respect All Players', desc = 'Harassment, discrimination, or toxic behavior will not be tolerated.' },
        { title = '2. No Random Violence (RDM)', desc = 'All violent RP must have a valid IC reason. No killing without initiation.' },
        { title = '3. No Vehicle Deathmatch (VDM)', desc = 'Do not use vehicles as weapons unless it is part of valid RP.' },
        { title = '4. No Metagaming', desc = 'Do not use out-of-character information in-character (discord, streams, etc).' },
        { title = '5. No Powergaming', desc = 'Do not force actions on other players without giving them a chance to react.' },
        { title = '6. Fear RP', desc = 'Value your character\'s life. When threatened, comply unless you have a clear advantage.' },
        { title = '7. No Combat Logging', desc = 'Do not disconnect to avoid RP situations. You must RP the scenario fully.' },
        { title = '8. New Life Rule', desc = 'After being revived, you do not remember the events leading to your death.' },
        { title = '9. Fail RP', desc = 'Stay in character at all times. No unrealistic actions or breaking immersion.' },
        { title = '10. Staff Respect', desc = 'Follow staff instructions. Disputes are handled via appeals, not in-game arguments.' },
    },
    keybinds = {
        { key = 'F1', action = 'Radial Menu — Vehicle controls, interactions, job actions' },
        { key = 'F2', action = 'Phone (NPWD) — Contacts, messages, banking, apps' },
        { key = 'F1 → Emotes', action = 'Radial Menu → Emotes section: Dances, Gestures, Walks, Expressions, etc.' },
        { key = 'X', action = 'Cancel Emote — Stop current animation' },
        { key = 'F5', action = 'Chat — IC chat, OOC chat, commands' },
        { key = 'F6', action = 'Job Menu — Job-specific actions and interactions' },
        { key = 'F11', action = 'Map — Full-screen GPS and waypoint map' },
        { key = 'M', action = 'Mini-Map — Toggle radar display on/off' },
        { key = 'U', action = 'Voice Proximity — Cycle through voice ranges' },
        { key = 'N', action = 'Phone Camera — Open phone camera for photos' },
        { key = 'L', action = 'Vehicle Lock — Lock/unlock nearest vehicle (requires keys)' },
        { key = 'B', action = 'Vehicle Engine — Toggle engine on/off' },
        { key = 'X', action = 'Hands Up — Raise hands in surrender' },
        { key = 'Z', action = 'Crouch — Toggle crouch stance' },
        { key = 'E (hold)', action = 'Vehicle Extraction (driver seat) — Extract target from vehicle while dragging' },
        { key = '/rules', action = 'This guide — View server rules, keybinds, and staff contacts' },
        { key = '/report', action = 'Report a player — Send a report to online staff' },
        { key = '/help', action = 'View available server commands' },
        { key = '/ooc', action = 'OOC Chat — Send out-of-character message' },
        { key = '/me', action = 'Me Command — Describe an action your character performs' },
        { key = '/do', action = 'Do Command — Describe the outcome of an action or environment' },
    },
    staff = {
        { role = 'Founder / Owner', name = 'Server Owner', contact = 'Discord: owner#0001' },
        { role = 'Head Administrator', name = 'Admin Name', contact = 'Discord: admin#0002' },
        { role = 'Senior Moderator', name = 'Mod Name', contact = 'Discord: mod#0003' },
        { role = 'Developer', name = 'Dev Name', contact = 'Discord: dev#0004' },
    },
    colors = {
        background = '#0f1923',
        card = '#1a2d3d',
        accent = '#00bcd4',
        text = '#e0e0e0',
        textMuted = '#8899aa',
        border = '#2a3f4f',
    }
}
