Config = Config or {}
Config.Phone = {
    apps = {
        { id = 'phone',      label = 'Phone',      icon = 'fas fa-phone',      color = '#34C759' },
        { id = 'messages',   label = 'Messages',   icon = 'fas fa-comment-dots', color = '#2196F3' },
        { id = 'contacts',   label = 'Contacts',   icon = 'fas fa-address-book', color = '#4CAF50' },
        { id = 'facetime',   label = 'FaceTime',   icon = 'fas fa-video',       color = '#5856D6' },
        { id = 'banking',    label = 'Banking',    icon = 'fas fa-university',   color = '#FF9800' },
        { id = 'photos',     label = 'Photos',     icon = 'fas fa-images',      color = '#FF2D55' },
        { id = 'camera',     label = 'Camera',     icon = 'fas fa-camera',      color = '#9C27B0' },
        { id = 'weather',    label = 'Weather',    icon = 'fas fa-cloud-sun',    color = '#00BCD4' },
        { id = 'maps',       label = 'Maps',       icon = 'fas fa-map',         color = '#34C759' },
        { id = 'music',      label = 'Music',      icon = 'fas fa-music',       color = '#FF2D55' },
        { id = 'social',     label = 'Social',     icon = 'fas fa-hashtag',     color = '#1DA1F2' },
        { id = 'blackchat',  label = 'Black Chat', icon = 'fas fa-lock',        color = '#8B0000' },
        { id = 'browser',    label = 'Browser',    icon = 'fas fa-globe',       color = '#00BCD4' },
        { id = 'notes',      label = 'Notes',      icon = 'fas fa-sticky-note',  color = '#FFD60A' },
        { id = 'calendar',   label = 'Calendar',   icon = 'fas fa-calendar',    color = '#FF3B30' },
        { id = 'clock',      label = 'Clock',      icon = 'fas fa-clock',       color = '#1C1C1E' },
        { id = 'calculator', label = 'Calc',       icon = 'fas fa-calculator',  color = '#333333' },
        { id = 'wallet',     label = 'Wallet',     icon = 'fas fa-wallet',      color = '#007AFF' },
        { id = 'settings',   label = 'Settings',   icon = 'fas fa-cog',         color = '#8E8E93' },
        { id = 'appstore',   label = 'App Store',  icon = 'fas fa-store',       color = '#007AFF' },
    },
    dockApps = { 'phone', 'messages', 'browser', 'music' },
    openKey = 244,
    defaultWallpaper = 'linear-gradient(135deg, #1a1a2e, #16213e, #0f3460)',
    maxContacts = 100,
    maxMessages = 500,
    messagesPerPage = 100,
    bankRefreshInterval = 30000,
    CallSettings = {
        maxCallDuration = 3600,
        ringDuration = 30,
        voicemailEnabled = true,
        voicemailMaxLength = 60,
        allowConference = false,
        pmaVoiceIntegration = true,
        callChannel = 'phone_call',
    },
    regionCodes = {
        { code = '+1', label = 'US' },
        { code = '+44', label = 'UK' },
        { code = '+61', label = 'AU' },
        { code = '+49', label = 'DE' },
        { code = '+33', label = 'FR' },
    },
    weatherApiKey = '',
    mapTilesUrl = 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
}
