Config = Config or {}

Config.CIDTerminal = {
    terminalLocations = {
        { name = 'cids_main', label = 'CID Management Terminal', coords = vector3(108.0, -742.0, 42.0), heading = 0.0 },
    },

    defaultGrades = {
        { grade = 0, label = 'Probationary Agent', salary = 500 },
        { grade = 1, label = 'Junior Agent', salary = 750 },
        { grade = 2, label = 'Agent', salary = 1000 },
        { grade = 3, label = 'Senior Agent', salary = 1250 },
        { grade = 4, label = 'Lead Agent', salary = 1500 },
        { grade = 5, label = 'Supervisor', salary = 1750 },
        { grade = 6, label = 'Unit Chief', salary = 2000 },
        { grade = 7, label = 'Deputy Director', salary = 2250 },
        { grade = 8, label = 'Director', salary = 2500 },
        { grade = 9, label = 'Deputy Commissioner', salary = 2750 },
        { grade = 10, label = 'Commissioner', salary = 3000 },
    },

    defaultArmoryItems = {
        { item = 'ammo-9', label = '9mm Pistol Ammo', rank = 0, price = 0, category = 'ammo' },
        { item = 'ammo-rifle', label = '5.56 Rifle Ammo', rank = 2, price = 0, category = 'ammo' },
        { item = 'armor', label = 'Body Armor', rank = 0, price = 0, category = 'equipment' },
        { item = 'radio', label = 'Radio', rank = 0, price = 0, category = 'equipment' },
        { item = 'handcuffs', label = 'Handcuffs', rank = 0, price = 0, category = 'equipment' },
        { item = 'spikestrip', label = 'Spike Strip', rank = 0, price = 0, category = 'equipment' },
        { item = 'roadflare', label = 'Road Flare', rank = 0, price = 0, category = 'equipment' },
        { item = 'medikit', label = 'Medical Kit', rank = 0, price = 0, category = 'equipment' },
        { item = 'ammo-rifle2', label = '7.62 Rifle Ammo', rank = 2, price = 0, category = 'ammo' },
        { item = 'at_flashlight', label = 'Tactical Flashlight', rank = 0, price = 0, category = 'equipment' },
        { item = 'at_suppressor_light', label = 'Suppressor', rank = 2, price = 0, category = 'equipment' },
        { item = 'WEAPON_BZGAS', label = 'BZ Tear Gas', rank = 2, price = 0, category = 'weapons' },
        { item = 'weapon_pistol', label = 'Service Pistol', rank = 0, price = 0, category = 'weapons' },
        { item = 'weapon_smg', label = 'Submachine Gun', rank = 2, price = 0, category = 'weapons' },
        { item = 'weapon_assaultrifle', label = 'Assault Rifle', rank = 3, price = 0, category = 'weapons' },
        { item = 'weapon_shotgun', label = 'Shotgun', rank = 3, price = 0, category = 'weapons' },
        { item = 'weapon_carbinerifle', label = 'Carbine Rifle', rank = 4, price = 0, category = 'weapons' },
        { item = 'weapon_pistol50', label = 'Pistol .50', rank = 1, price = 0, category = 'weapons' },
        { item = 'weapon_combatpdw', label = 'Combat PDW', rank = 2, price = 0, category = 'weapons' },
        { item = 'weapon_microsmg', label = 'Micro SMG', rank = 2, price = 0, category = 'weapons' },
        { item = 'weapon_assaultshotgun', label = 'Assault Shotgun', rank = 3, price = 0, category = 'weapons' },
        { item = 'weapon_pumpshotgun', label = 'Pump Shotgun', rank = 2, price = 0, category = 'weapons' },
        { item = 'weapon_specialcarbine', label = 'Special Carbine', rank = 3, price = 0, category = 'weapons' },
        { item = 'weapon_advancedrifle', label = 'Advanced Rifle', rank = 4, price = 0, category = 'weapons' },
        { item = 'weapon_bullpuprifle', label = 'Bullpup Rifle', rank = 3, price = 0, category = 'weapons' },
        { item = 'weapon_heavysniper', label = 'Heavy Sniper', rank = 4, price = 0, category = 'weapons' },
        { item = 'weapon_marksmanrifle', label = 'Marksman Rifle', rank = 3, price = 0, category = 'weapons' },
        { item = 'weapon_militaryrifle', label = 'Military Rifle', rank = 4, price = 0, category = 'weapons' },
        { item = 'weapon_nightstick', label = 'Nightstick', rank = 0, price = 0, category = 'weapons' },
        { item = 'lockpick', label = 'Lockpick', rank = 0, price = 0, category = 'equipment' },
        { item = 'heist_mask', label = 'Head Bag', rank = 0, price = 0, category = 'equipment' },
        { item = 'repair_kit', label = 'Repair Kit', rank = 0, price = 0, category = 'equipment' },
        { item = 'fingerprint_kit', label = 'Fingerprint Kit', rank = 0, price = 0, category = 'cid' },
        { item = 'casing_kit', label = 'Casing Collection Kit', rank = 0, price = 0, category = 'cid' },
        { item = 'dna_swab', label = 'DNA Swab Kit', rank = 0, price = 0, category = 'cid' },
        { item = 'evidence_bag', label = 'Evidence Bag', rank = 0, price = 0, category = 'cid' },
        { item = 'cid_laptop', label = 'CID Laptop', rank = 0, price = 0, category = 'cid' },
        { item = 'drone', label = 'Surveillance Drone', rank = 3, price = 0, category = 'cid' },
        { item = 'surveillance_camera', label = 'Pen Camera', rank = 1, price = 0, category = 'cid' },
        { item = 'audio_bug', label = 'Audio Bug', rank = 1, price = 0, category = 'cid' },
        { item = 'gps_tracker', label = 'GPS Tracker', rank = 1, price = 0, category = 'cid' },
        { item = 'tracker_sweeper', label = 'Tracker Sweeper', rank = 1, price = 0, category = 'cid' },
        { item = 'cid_bug_pen', label = 'Pen Camera Bug', rank = 1, price = 0, category = 'cid' },
        { item = 'cid_bug_audio', label = 'Audio Bug', rank = 1, price = 0, category = 'cid' },
        { item = 'cid_gps_tracker', label = 'GPS Tracker', rank = 1, price = 0, category = 'cid' },
        { item = 'cid_covert_entry', label = 'Covert Entry Kit', rank = 2, price = 0, category = 'cid' },
        { item = 'cid_lockpick', label = 'CID Lockpick', rank = 2, price = 0, category = 'cid' },
        { item = 'cid_alarm_bypass', label = 'Alarm Bypass Tool', rank = 2, price = 0, category = 'cid' },
        { item = 'cid_evidence_bag', label = 'Evidence Collection Kit', rank = 0, price = 0, category = 'cid' },
        { item = 'radar_gun', label = 'Radar Gun', rank = 0, price = 0, category = 'equipment' },
        { item = 'traffic_cone', label = 'Traffic Cone', rank = 0, price = 0, category = 'equipment' },
        { item = 'barrier', label = 'Road Barrier', rank = 0, price = 0, category = 'equipment' },
    },

    allowedJobs = { 'cid', 'police' },
    manageJobs = { 'cid' },
    minRankToManage = 3,
}
