Config = Config or {}
Config.AdvancedHousing = {
    properties = {
        {
            id = 'apartment_01',
            name = 'Downtown Studio',
            price = 250000,
            coords = vector3(266.1, -1007.2, -101.0),
            interior = 'apartment1',
            rooms = { 'living_room', 'bedroom', 'kitchen', 'bathroom' },
            garageSlots = 1,
            storageWeight = 50000,
            blip = { id = 40, color = 3 },
        },
        {
            id = 'apartment_02',
            name = 'Vinewood Loft',
            price = 450000,
            coords = vector3(-285.1, 640.3, 170.0),
            interior = 'apartment2',
            rooms = { 'living_room', 'bedroom', 'kitchen', 'bathroom', 'office' },
            garageSlots = 2,
            storageWeight = 75000,
            blip = { id = 40, color = 3 },
        },
        {
            id = 'house_01',
            name = 'Paleto Bay House',
            price = 350000,
            coords = vector3(-167.7, 6470.7, 31.6),
            interior = 'house1',
            rooms = { 'living_room', 'bedroom', 'bedroom2', 'kitchen', 'bathroom', 'garage' },
            garageSlots = 2,
            storageWeight = 100000,
            blip = { id = 40, color = 2 },
        },
        {
            id = 'house_02',
            name = 'Rockford Hills Estate',
            price = 1200000,
            coords = vector3(-773.8, 319.0, 85.7),
            interior = 'house2',
            rooms = { 'living_room', 'dining_room', 'kitchen', 'master_bedroom', 'bedroom2', 'bedroom3', 'bathroom', 'bathroom2', 'office', 'garage' },
            garageSlots = 4,
            storageWeight = 200000,
            blip = { id = 40, color = 5 },
        },
        {
            id = 'house_03',
            name = 'Sandy Shores Trailer',
            price = 80000,
            coords = vector3(1502.6, 3921.3, 30.8),
            interior = 'trailer',
            rooms = { 'living_room', 'bedroom', 'kitchen' },
            garageSlots = 1,
            storageWeight = 25000,
            blip = { id = 40, color = 1 },
        },
        {
            id = 'mansion_01',
            name = 'Richman Mansion',
            price = 3500000,
            coords = vector3(-1381.1, 22.4, 53.1),
            interior = 'mansion',
            rooms = { 'living_room', 'dining_room', 'kitchen', 'master_bedroom', 'bedroom2', 'bedroom3', 'bedroom4', 'bathroom', 'bathroom2', 'bathroom3', 'office', 'gym', 'pool', 'garage' },
            garageSlots = 6,
            storageWeight = 500000,
            blip = { id = 40, color = 7 },
        },
    },
    furniture = {
        { id = 'couch_01', name = 'Leather Couch', model = 'apa_mp_h_sofa_01', category = 'seating', price = 5000, placeholder = 'chair' },
        { id = 'couch_02', name = 'Modern Sofa', model = 'apa_mp_h_sofa_02', category = 'seating', price = 7500, placeholder = 'chair' },
        { id = 'table_01', name = 'Coffee Table', model = 'apa_mp_h_tab_coffee_01', category = 'tables', price = 3000, placeholder = 'prop_table_01' },
        { id = 'table_02', name = 'Dining Table', model = 'apa_mp_h_tab_dining_01', category = 'tables', price = 8000, placeholder = 'prop_table_02' },
        { id = 'bed_01', name = 'Queen Bed', model = 'apa_mp_h_bed_01', category = 'beds', price = 10000, placeholder = 'v_res_tre_bed1' },
        { id = 'bed_02', name = 'King Bed', model = 'apa_mp_h_bed_02', category = 'beds', price = 15000, placeholder = 'v_res_mp_bed' },
        { id = 'lamp_01', name = 'Floor Lamp', model = 'apa_mp_h_lamp_01', category = 'lighting', price = 2000, placeholder = 'prop_floor_lamp_01' },
        { id = 'lamp_02', name = 'Desk Lamp', model = 'apa_mp_h_lamp_02', category = 'lighting', price = 1000, placeholder = 'prop_desk_lamp' },
        { id = 'tv_01', name = 'Flat Screen TV', model = 'apa_mp_h_tv_01', category = 'electronics', price = 12000, placeholder = 'prop_tv_flat_01' },
        { id = 'tv_02', name = 'Wall TV', model = 'apa_mp_h_tv_02', category = 'electronics', price = 18000, placeholder = 'prop_tv_flat_mount' },
        { id = 'shelf_01', name = 'Bookshelf', model = 'apa_mp_h_shelf_01', category = 'storage', price = 4000, placeholder = 'prop_bookcase_01' },
        { id = 'cabinet_01', name = 'Kitchen Cabinet', model = 'apa_mp_h_cab_01', category = 'storage', price = 6000, placeholder = 'prop_cabinet_01' },
        { id = 'rug_01', name = 'Large Rug', model = 'apa_mp_h_rug_01', category = 'decor', price = 2500, placeholder = 'prop_rug_maker_01' },
        { id = 'painting_01', name = 'Wall Painting', model = 'apa_mp_h_paint_01', category = 'decor', price = 3500, placeholder = 'prop_painting_01' },
        { id = 'plant_01', name = 'Potted Plant', model = 'apa_mp_h_plant_01', category = 'plants', price = 1500, placeholder = 'prop_plant_int_01' },
    },
    alarm = {
        prices = { install = 5000, monthly = 2000 },
        securityLevels = { basic = { delay = 30, policeNotify = true }, premium = { delay = 15, policeNotify = true, ownerNotify = true } },
    },
    guestKeyPrice = 1000,
    sellRefundPercent = 0.6,
    storageItemLimit = 50,
    interiorCoords = {
        apartment1 = { enter = vector3(266.1, -1007.2, -101.0), exit = vector3(266.1, -1007.2, -26.0) },
        apartment2 = { enter = vector3(-285.1, 640.3, 170.0), exit = vector3(-285.1, 640.3, 30.0) },
        house1 = { enter = vector3(-167.7, 6470.7, 31.6), exit = vector3(-167.7, 6470.7, 20.0) },
        house2 = { enter = vector3(-773.8, 319.0, 85.7), exit = vector3(-773.8, 319.0, 60.0) },
        trailer = { enter = vector3(1502.6, 3921.3, 30.8), exit = vector3(1502.6, 3921.3, 20.0) },
        mansion = { enter = vector3(-1381.1, 22.4, 53.1), exit = vector3(-1381.1, 22.4, 30.0) },
    },
    adminGroups = { 'admin', 'superadmin', 'god' },
}
