Config = Config or {}
Config.TrashCans = Config.TrashCans or {}

Config.TrashCans = {
    maxDistance = 2.0,
    searchTime = 3000,
    trashEffect = 'scr_amb_cinema',
    cooldown = 300,

    propModels = {
        'prop_bin_01a',
        'prop_bin_02a',
        'prop_bin_03a',
        'prop_bin_04a',
        'prop_bin_05a',
        'prop_bin_06a',
        'prop_bin_07a',
        'prop_bin_08a',
        'prop_bin_10a',
        'prop_bin_11a',
        'prop_bin_12a',
        'prop_bin_13a',
        'prop_bin_14a',
        'prop_bin_15a',
        'prop_bin_bc_01',
        'prop_bin_bc_02',
        'prop_bin_beach_01a',
        'prop_bin_beach_01a_dmg',
        'prop_bin_delp_01',
        'prop_bin_delp_02',
        'prop_bin_delp_03',
        'prop_bin_delp_04',
        'prop_bin_delp_05',
        'prop_dumpster_01a',
        'prop_dumpster_02a',
        'prop_dumpster_03a',
        'prop_dumpster_04a',
        'prop_dumpster_04b',
        'prop_dumpster_4a',
        'prop_dumpster_4b',
    },

    lootTable = {
        junk = {
            { item = 'empty_can', label = 'Empty Can', min = 1, max = 3, weight = 50 },
            { item = 'rotten_food', label = 'Rotten Food', min = 1, max = 1, weight = 30 },
            { item = 'wet_newspaper', label = 'Wet Newspaper', min = 1, max = 1, weight = 40 },
            { item = 'broken_toy', label = 'Broken Toy', min = 1, max = 1, weight = 20 },
            { item = 'used_needle', label = 'Used Needle', min = 1, max = 1, weight = 5 },
            { item = 'dirty_rag', label = 'Dirty Rag', min = 1, max = 2, weight = 35 },
        },
        valuables = {
            { item = 'gold_watch', label = 'Gold Watch', min = 1, max = 1, weight = 3 },
            { item = 'diamond_ring', label = 'Diamond Ring', min = 1, max = 1, weight = 1 },
            { item = 'cash', label = 'Cash', min = 5, max = 50, weight = 15 },
            { item = 'silver_chain', label = 'Silver Chain', min = 1, max = 1, weight = 2 },
            { item = 'old_phone', label = 'Old Phone', min = 1, max = 1, weight = 5 },
            { item = 'valuable_vase', label = 'Valuable Vase', min = 1, max = 1, weight = 1 },
        },
        evidence = {
            { item = 'burned_photo', label = 'Burned Photo', min = 1, max = 1, weight = 2 },
            { item = 'bloody_knife', label = 'Bloody Knife', min = 1, max = 1, weight = 1 },
            { item = 'drug_package', label = 'Drug Package', min = 1, max = 1, weight = 3 },
            { item = 'stolen_wallet', label = 'Stolen Wallet', min = 1, max = 1, weight = 2 },
            { item = 'phone_sim', label = 'Phone SIM Card', min = 1, max = 1, weight = 2 },
            { item = 'lockpick', label = 'Lockpick', min = 1, max = 1, weight = 1 },
            { item = 'usb_drive', label = 'USB Drive', min = 1, max = 1, weight = 2 },
        },
    },
}
