Config = Config or {}

Config.Dealership = {
    Locations = {
        {
            name = 'Premium Deluxe Motorsport',
            coords = vec3(-42.46, -1100.75, 26.42),
            ped = 'a_m_y_business_03',
            pedCoords = vec4(-45.34, -1098.0, 26.42, 70.0),
            categories = { 'compacts', 'sedans', 'sports', 'sportsclassics', 'super', 'muscle', 'offroad', 'suvs', 'coupes', 'cycles' },
            isOpen = function() return true end,
            blip = { sprite = 431, color = 2, scale = 0.7, label = 'Dealership' }
        },
        {
            name = 'Airport Hangar',
            coords = vec3(-1239.87, -3305.25, 13.94),
            ped = 'a_m_y_business_03',
            pedCoords = vec4(-1242.0, -3302.0, 13.94, 120.0),
            categories = { 'planes', 'helicopters' },
            isOpen = function() return true end,
            blip = { sprite = 431, color = 47, scale = 0.7, label = 'Air Vehicle Dealer' }
        },
        {
            name = 'Marina Boat Shop',
            coords = vec3(-734.52, -1310.75, 5.0),
            ped = 'a_m_y_business_03',
            pedCoords = vec4(-737.0, -1308.0, 5.0, 210.0),
            categories = { 'boats' },
            isOpen = function() return true end,
            blip = { sprite = 431, color = 54, scale = 0.7, label = 'Boat Dealer' }
        }
    },
    TestDriveDuration = 120,
    TestDriveCooldown = 300,
    DeliveryFee = 250,
    TradeInMultiplier = 0.6,
    PreviewSpawnOffset = vec3(20.0, 0.0, 0.0),
    MaxSpawnedPreviews = 3,
    Categories = {
        compacts = 'Compacts',
        sedans = 'Sedans',
        suvs = 'SUVs',
        coupes = 'Coupes',
        sports = 'Sports',
        sportsclassics = 'Sports Classics',
        super = 'Super',
        muscle = 'Muscle',
        offroad = 'Off-Road',
        cycles = 'Motorcycles',
        planes = 'Planes',
        helicopters = 'Helicopters',
        boats = 'Boats'
    },
    Financing = {
        InterestRate = 0.15,
        MinDownPayment = 0.2,
        WeeklyPaymentTerm = 20,
        EarlyPayoffPenalty = 0.03,
        MaxFinancingVehicles = 2
    }
}

Config.DealershipVehicles = {
    compacts = {
        { model = 'blista', price = 8000, financingPrice = 9200, stock = 10, description = 'Compact and efficient city car.' },
        { model = 'panto', price = 5000, financingPrice = 5750, stock = 8, description = 'Tiny car for tight spaces.' }
    },
    sedans = {
        { model = 'emperor', price = 8000, financingPrice = 9200, stock = 10, description = 'Classic sedan, reliable and cheap.' },
        { model = 'fugitive', price = 35000, financingPrice = 40250, stock = 6, description = 'Sporty four-door sedan.' },
        { model = 'intruder', price = 18000, financingPrice = 20700, stock = 8, description = 'Sleek family sedan.' },
        { model = 'premier', price = 15000, financingPrice = 17250, stock = 7, description = 'Affordable everyday sedan.' },
        { model = 'schafter2', price = 25000, financingPrice = 28750, stock = 5, description = 'Luxury executive sedan.' },
        { model = 'superd', price = 55000, financingPrice = 63250, stock = 4, description = 'High-end luxury sedan.' },
        { model = 'tailgater', price = 32000, financingPrice = 36800, stock = 6, description = 'Premium four-door comfort.' },
        { model = 'washington', price = 12000, financingPrice = 13800, stock = 9, description = 'Traditional American sedan.' },
        { model = 'asterope', price = 22000, financingPrice = 25300, stock = 7, description = 'Reliable mid-range sedan.' },
        { model = 'cognoscenti', price = 95000, financingPrice = 109250, stock = 3, description = 'Top-tier luxury sedan.' }
    },
    suvs = {
        { model = 'baller', price = 45000, financingPrice = 51750, stock = 6, description = 'Luxury SUV with presence.' },
        { model = 'baller2', price = 55000, financingPrice = 63250, stock = 5, description = 'Sporty luxury SUV.' },
        { model = 'mesa', price = 22000, financingPrice = 25300, stock = 7, description = 'Rugged off-road SUV.' },
        { model = 'patriot', price = 35000, financingPrice = 40250, stock = 5, description = 'Heavy-duty American SUV.' },
        { model = 'seminole', price = 18000, financingPrice = 20700, stock = 8, description = 'Compact SUV for city driving.' },
        { model = 'serrano', price = 28000, financingPrice = 32200, stock = 6, description = 'Stylish crossover SUV.' },
        { model = 'xls', price = 42000, financingPrice = 48300, stock = 5, description = 'Premium luxury SUV.' },
        { model = 'granger', price = 38000, financingPrice = 43700, stock = 4, description = 'Spacious family SUV.' },
        { model = 'huntley', price = 48000, financingPrice = 55200, stock = 4, description = 'High-performance luxury SUV.' },
        { model = 'landstalker', price = 20000, financingPrice = 23000, stock = 7, description = 'Classic full-size SUV.' }
    },
    coupes = {
        { model = 'cogcabrio', price = 65000, financingPrice = 74750, stock = 4, description = 'Luxury convertible coupe.' },
        { model = 'exemplar', price = 55000, financingPrice = 63250, stock = 4, description = 'Elegant four-door coupe.' },
        { model = 'f620', price = 42000, financingPrice = 48300, stock = 5, description = 'Sleek Italian-styled coupe.' },
        { model = 'felon', price = 35000, financingPrice = 40250, stock = 6, description = 'Refined luxury grand tourer.' },
        { model = 'felon2', price = 38000, financingPrice = 43700, stock = 5, description = 'Convertible grand tourer.' },
        { model = 'jackal', price = 32000, financingPrice = 36800, stock = 6, description = 'Aggressive sports coupe.' },
        { model = 'oracle', price = 42000, financingPrice = 48300, stock = 5, description = 'Executive luxury coupe.' },
        { model = 'oracle2', price = 48000, financingPrice = 55200, stock = 4, description = 'Updated luxury coupe.' },
        { model = 'sentinel', price = 28000, financingPrice = 32200, stock = 6, description = 'Entry-level luxury coupe.' },
        { model = 'sentinel2', price = 32000, financingPrice = 36800, stock = 5, description = 'Convertible luxury coupe.' }
    },
    sports = {
        { model = 'alpha', price = 75000, financingPrice = 86250, stock = 4, description = 'Lightweight sports car.' },
        { model = 'banshee', price = 65000, financingPrice = 74750, stock = 4, description = 'Classic American sports car.' },
        { model = 'bestiagts', price = 85000, financingPrice = 97750, stock = 3, description = 'British racing heritage.' },
        { model = 'blista2', price = 25000, financingPrice = 28750, stock = 6, description = 'Sporty compact hatch.' },
        { model = 'buffalo', price = 45000, financingPrice = 51750, stock = 5, description = 'Modern muscle sports car.' },
        { model = 'buffalo2', price = 55000, financingPrice = 63250, stock = 4, description = 'Upgraded sports coupe.' },
        { model = 'carbonizzare', price = 95000, financingPrice = 109250, stock = 3, description = 'Convertible sports car.' },
        { model = 'comet2', price = 85000, financingPrice = 97750, stock = 3, description = 'Rear-engine sports car.' },
        { model = 'coquette', price = 78000, financingPrice = 89700, stock = 4, description = 'American sports icon.' },
        { model = 'feltzer2', price = 65000, financingPrice = 74750, stock = 4, description = 'Precision German sports car.' },
        { model = 'furoregt', price = 88000, financingPrice = 101200, stock = 3, description = 'Aggressive track-focused coupe.' },
        { model = 'fusilade', price = 35000, financingPrice = 40250, stock = 5, description = 'Sporty everyday driver.' },
        { model = 'jester', price = 75000, financingPrice = 86250, stock = 4, description = 'Japanese sports legend.' },
        { model = 'khamelion', price = 70000, financingPrice = 80500, stock = 3, description = 'Electric sports car.' },
        { model = 'kuruma', price = 55000, financingPrice = 63250, stock = 4, description = 'Rally-bred sports sedan.' },
        { model = 'massacro', price = 82000, financingPrice = 94300, stock = 3, description = 'Elegant grand tourer.' },
        { model = 'ninef', price = 88000, financingPrice = 101200, stock = 3, description = 'Exotic Italian sports car.' },
        { model = 'ninef2', price = 92000, financingPrice = 105800, stock = 2, description = 'Convertible exotic.' },
        { model = 'omnis', price = 58000, financingPrice = 66700, stock = 4, description = 'Rally-inspired sports car.' },
        { model = 'penumbra', price = 28000, financingPrice = 32200, stock = 6, description = 'Affordable sports coupe.' },
        { model = 'rapidgt', price = 75000, financingPrice = 86250, stock = 4, description = 'British grand tourer.' },
        { model = 'rapidgt2', price = 82000, financingPrice = 94300, stock = 3, description = 'Convertible grand tourer.' },
        { model = 'schwarzer', price = 48000, financingPrice = 55200, stock = 5, description = 'German sports coupe.' },
        { model = 'seven70', price = 92000, financingPrice = 105800, stock = 2, description = 'Modern luxury sports car.' },
        { model = 'sultan', price = 32000, financingPrice = 36800, stock = 5, description = 'Japanese rally sedan.' },
        { model = 'surano', price = 78000, financingPrice = 89700, stock = 3, description = 'Convertible sports car.' },
        { model = 'tropos', price = 62000, financingPrice = 71300, stock = 4, description = 'Retro rally sports car.' },
        { model = 'verlierer', price = 95000, financingPrice = 109250, stock = 2, description = 'Aggressive track weapon.' }
    },
    sportsclassics = {
        { model = 'btype', price = 85000, financingPrice = 97750, stock = 3, description = 'Classic vintage roadster.' },
        { model = 'btype2', price = 95000, financingPrice = 109250, stock = 2, description = 'Hot rod classic.' },
        { model = 'btype3', price = 110000, financingPrice = 126500, stock = 2, description = 'Luxury vintage racer.' },
        { model = 'casco', price = 95000, financingPrice = 109250, stock = 3, description = 'Classic Italian grand tourer.' },
        { model = 'coquette2', price = 68000, financingPrice = 78200, stock = 4, description = 'Classic American sports car.' },
        { model = 'coquette3', price = 75000, financingPrice = 86250, stock = 3, description = 'Modern classic Corvette.' },
        { model = 'infernus2', price = 120000, financingPrice = 138000, stock = 2, description = 'Retro supercar icon.' },
        { model = 'jb700', price = 58000, financingPrice = 66700, stock = 4, description = 'Classic spyder with gadgets.' },
        { model = 'mamba', price = 105000, financingPrice = 120750, stock = 2, description = 'Muscle-bound classic roadster.' },
        { model = 'manana', price = 15000, financingPrice = 17250, stock = 8, description = 'Lowrider classic cruiser.' },
        { model = 'monroe', price = 98000, financingPrice = 112700, stock = 2, description = 'Classic endurance racer.' },
        { model = 'pigalle', price = 55000, financingPrice = 63250, stock = 4, description = 'French classic coupe.' },
        { model = 'rapidgt3', price = 85000, financingPrice = 97750, stock = 3, description = 'Classic British grand tourer.' },
        { model = 'retinue', price = 28000, financingPrice = 32200, stock = 6, description = 'Classic rally car.' },
        { model = 'stinger', price = 95000, financingPrice = 109250, stock = 2, description = 'Classic Italian roadster.' },
        { model = 'stingergt', price = 105000, financingPrice = 120750, stock = 2, description = 'Track-focused classic.' },
        { model = 'torero', price = 88000, financingPrice = 101200, stock = 3, description = 'Classic Lamborghini style.' },
        { model = 'tornado', price = 12000, financingPrice = 13800, stock = 8, description = 'Classic lowrider.' },
        { model = 'tornado2', price = 18000, financingPrice = 20700, stock = 6, description = 'Convertible classic.' },
        { model = 'turismo2', price = 115000, financingPrice = 132250, stock = 2, description = 'Retro Ferrari-inspired supercar.' },
        { model = 'viseris', price = 125000, financingPrice = 143750, stock = 2, description = 'Classic supercar legend.' },
        { model = 'ztype', price = 135000, financingPrice = 155250, stock = 1, description = 'Ultra-rare vintage supercar.' }
    },
    super = {
        { model = 'adder', price = 250000, financingPrice = 287500, stock = 2, description = 'Ultimate hypercar.' },
        { model = 'autarch', price = 350000, financingPrice = 402500, stock = 1, description = 'Track-bred hypercar.' },
        { model = 'banshee2', price = 185000, financingPrice = 212750, stock = 2, description = 'High-performance roadster.' },
        { model = 'bullet', price = 155000, financingPrice = 178250, stock = 3, description = 'Ford GT-inspired supercar.' },
        { model = 'cheetah', price = 220000, financingPrice = 253000, stock = 2, description = 'Iconic supercar.' },
        { model = 'entityxf', price = 275000, financingPrice = 316250, stock = 2, description = 'Koeningsegg-inspired hypercar.' },
        { model = 'fmj', price = 285000, financingPrice = 327750, stock = 1, description = 'American hypercar.' },
        { model = 'infernus', price = 220000, financingPrice = 253000, stock = 2, description = 'Lamborghini-inspired icon.' },
        { model = 'nero', price = 300000, financingPrice = 345000, stock = 1, description = 'Bugatti-inspired hypercar.' },
        { model = 'nero2', price = 320000, financingPrice = 368000, stock = 1, description = 'Custom hypercar variant.' },
        { model = 'osiris', price = 260000, financingPrice = 299000, stock = 2, description = 'Refined hypercar.' },
        { model = 'penetrator', price = 195000, financingPrice = 224250, stock = 2, description = 'Aggressive supercar.' },
        { model = 'pfister811', price = 290000, financingPrice = 333500, stock = 1, description = 'Porsche 918-inspired hypercar.' },
        { model = 'reaper', price = 280000, financingPrice = 322000, stock = 1, description = 'Lamborghini-inspired hypercar.' },
        { model = 'sultanrs', price = 45000, financingPrice = 51750, stock = 4, description = 'Race-bred sports car.' },
        { model = 't20', price = 320000, financingPrice = 368000, stock = 1, description = 'McLaren P1-inspired hypercar.' },
        { model = 'turismor', price = 275000, financingPrice = 316250, stock = 2, description = 'Refined Ferrari-inspired supercar.' },
        { model = 'tyrus', price = 255000, financingPrice = 293250, stock = 2, description = 'Track-focused hypercar.' },
        { model = 'vacca', price = 120000, financingPrice = 138000, stock = 3, description = 'Entry-level supercar.' },
        { model = 'voltic', price = 100000, financingPrice = 115000, stock = 3, description = 'Electric supercar.' },
        { model = 'le7b', price = 380000, financingPrice = 437000, stock = 1, description = 'Ultimate track weapon.' },
        { model = 'xa21', price = 310000, financingPrice = 356500, stock = 1, description = 'Next-gen hybrid hypercar.' },
        { model = 'visione', price = 290000, financingPrice = 333500, stock = 1, description = 'Futuristic hypercar.' },
        { model = 'prototipo', price = 420000, financingPrice = 483000, stock = 1, description = 'Rare concept hypercar.' },
        { model = 'sc1', price = 230000, financingPrice = 264500, stock = 2, description = 'Modern supercar.' }
    },
    muscle = {
        { model = 'blade', price = 32000, financingPrice = 36800, stock = 5, description = 'Classic muscle coupe.' },
        { model = 'buccaneer', price = 18000, financingPrice = 20700, stock = 7, description = 'Classic cruiser.' },
        { model = 'buccaneer2', price = 25000, financingPrice = 28750, stock = 5, description = 'Custom cruiser.' },
        { model = 'chino', price = 15000, financingPrice = 17250, stock = 7, description = 'Lowrider classic.' },
        { model = 'chino2', price = 22000, financingPrice = 25300, stock = 5, description = 'Custom lowrider.' },
        { model = 'clique', price = 42000, financingPrice = 48300, stock = 4, description = 'Retro muscle coupe.' },
        { model = 'coquette4', price = 55000, financingPrice = 63250, stock = 4, description = 'Modern muscle icon.' },
        { model = 'deviant', price = 48000, financingPrice = 55200, stock = 4, description = 'Aggressive muscle coupe.' },
        { model = 'dominator', price = 35000, financingPrice = 40250, stock = 5, description = 'Modern muscle legend.' },
        { model = 'dominator2', price = 42000, financingPrice = 48300, stock = 4, description = 'Classic muscle legend.' },
        { model = 'dominator3', price = 52000, financingPrice = 59800, stock = 3, description = 'Track-ready muscle.' },
        { model = 'dukes', price = 25000, financingPrice = 28750, stock = 6, description = 'Classic American muscle.' },
        { model = 'dukes2', price = 38000, financingPrice = 43700, stock = 4, description = 'Beefed-up muscle.' },
        { model = 'ellie', price = 45000, financingPrice = 51750, stock = 4, description = 'Classic Ford Mustang style.' },
        { model = 'faction', price = 22000, financingPrice = 25300, stock = 6, description = 'Classic muscle coupe.' },
        { model = 'faction2', price = 32000, financingPrice = 36800, stock = 4, description = 'Custom faction.' },
        { model = 'faction3', price = 45000, financingPrice = 51750, stock = 3, description = 'Lowrider faction.' },
        { model = 'gauntlet', price = 28000, financingPrice = 32200, stock = 5, description = 'Modern muscle coupe.' },
        { model = 'gauntlet2', price = 35000, financingPrice = 40250, stock = 4, description = 'Reinforced muscle.' },
        { model = 'gauntlet3', price = 25000, financingPrice = 28750, stock = 5, description 'Classic muscle.' },
        { model = 'gauntlet4', price = 42000, financingPrice = 48300, stock = 3, description = 'Custom performance muscle.' },
        { model = 'hermes', price = 28000, financingPrice = 32200, stock = 5, description = 'Classic lowrider.' },
        { model = 'hotknife', price = 35000, financingPrice = 40250, stock = 4, description = 'Rat rod classic.' },
        { model = 'hustler', price = 28000, financingPrice = 32200, stock = 5, description = 'Classic hot rod.' },
        { model = 'impaler', price = 32000, financingPrice = 36800, stock = 5, description = 'Classic muscle beast.' },
        { model = 'impaler2', price = 42000, financingPrice = 48300, stock = 3, description = 'Custom muscle.' },
        { model = 'nightshade', price = 48000, financingPrice = 55200, stock = 3, description = 'Aggressive muscle coupe.' },
        { model = 'phoenix', price = 22000, financingPrice = 25300, stock = 6, description = 'Firebird classic.' },
        { model = 'picador', price = 12000, financingPrice = 13800, stock = 7, description = 'Muscle pickup.' },
        { model = 'ruiner', price = 25000, financingPrice = 28750, stock = 5, description = 'Performance muscle.' },
        { model = 'sabregt', price = 22000, financingPrice = 25300, stock = 6, description = 'Classic muscle.' },
        { model = 'sabregt2', price = 32000, financingPrice = 36800, stock = 4, description = 'Custom muscle.' },
        { model = 'slamvan', price = 15000, financingPrice = 17250, stock = 6, description = 'Classic lowrider truck.' },
        { model = 'slamvan2', price = 25000, financingPrice = 28750, stock = 5, description = 'Custom lowrider truck.' },
        { model = 'slamvan3', price = 35000, financingPrice = 40250, stock = 3, description = 'Show truck.' },
        { model = 'stalion', price = 18000, financingPrice = 20700, stock = 6, description = 'Classic pony car.' },
        { model = 'stalion2', price = 35000, financingPrice = 40250, stock = 4, description = 'Custom drift pony.' },
        { model = 'tampa', price = 25000, financingPrice = 28750, stock = 5, description = 'Classic muscle coupe.' },
        { model = 'tampa2', price = 42000, financingPrice = 48300, stock = 3, description = 'Drift-tuned muscle.' },
        { model = 'vigero', price = 15000, financingPrice = 17250, stock = 6, description = 'Classic Camaro style.' },
        { model = 'virgo', price = 18000, financingPrice = 20700, stock = 6, description = 'Classic lowrider.' },
        { model = 'virgo2', price = 28000, financingPrice = 32200, stock = 4, description = 'Custom lowrider.' },
        { model = 'virgo3', price = 35000, financingPrice = 40250, stock = 3, description = 'Luxury lowrider.' },
        { model = 'voxel', price = 52000, financingPrice = 59800, stock = 3, description = 'Modern retro muscle.' },
        { model = 'yosemite', price = 32000, financingPrice = 36800, stock = 4, description = 'Classic pickup.' }
    },
    offroad = {
        { model = 'bifta', price = 25000, financingPrice = 28750, stock = 5, description = 'Dune buggy fun.' },
        { model = 'blazer', price = 12000, financingPrice = 13800, stock = 7, description = 'ATV for off-road.' },
        { model = 'blazer2', price = 18000, financingPrice = 20700, stock = 5, description = 'Lifted off-roader.' },
        { model = 'blazer3', price = 22000, financingPrice = 25300, stock = 4, description = 'Heavy-duty ATV.' },
        { model = 'blazer4', price = 15000, financingPrice = 17250, stock = 6, description = 'Sport ATV.' },
        { model = 'brawler', price = 45000, financingPrice = 51750, stock = 4, description = 'Rally raid beast.' },
        { model = 'dubsta3', price = 35000, financingPrice = 40250, stock = 4, description = 'Lifted 6x6 truck.' },
        { model = 'dune', price = 28000, financingPrice = 32200, stock = 5, description = 'Off-road buggy.' },
        { model = 'guardian', price = 55000, financingPrice = 63250, stock = 3, description = 'Massive off-road truck.' },
        { model = 'insurgent', price = 135000, financingPrice = 155250, stock = 2, description = 'Armored off-roader.' },
        { model = 'kamacho', price = 42000, financingPrice = 48300, stock = 4, description = 'Trophy truck.' },
        { model = 'kalahari', price = 15000, financingPrice = 17250, stock = 6, description = 'Beach buggy.' },
        { model = 'outlaw', price = 35000, financingPrice = 40250, stock = 4, description = 'Retro off-roader.' },
        { model = 'rancherxl', price = 18000, financingPrice = 20700, stock = 6, description = 'Classic off-road SUV.' },
        { model = 'rebel', price = 12000, financingPrice = 13800, stock = 7, description = 'Off-road pickup.' },
        { model = 'rebel2', price = 22000, financingPrice = 25300, stock = 5, description = 'Custom off-road pickup.' },
        { model = 'riata', price = 32000, financingPrice = 36800, stock = 5, description = 'Modern off-roader.' },
        { model = 'sandking', price = 25000, financingPrice = 28750, stock = 5, description = 'Massive off-road truck.' },
        { model = 'sandking2', price = 32000, financingPrice = 36800, stock = 4, description = 'Lifted off-road truck.' },
        { model = 'trophytruck', price = 55000, financingPrice = 63250, stock = 3, description = 'Race trophy truck.' },
        { model = 'trophytruck2', price = 65000, financingPrice = 74750, stock = 2, description = 'Custom trophy truck.' },
        { model = 'mesa3', price = 28000, financingPrice = 32200, stock = 5, description = 'Lifted off-road Jeep.' }
    },
    cycles = {
        { model = 'akuma', price = 15000, financingPrice = 17250, stock = 6, description = 'Sport motorcycle.' },
        { model = 'avarus', price = 18000, financingPrice = 20700, stock = 5, description = 'Cruiser motorcycle.' },
        { model = 'bagger', price = 12000, financingPrice = 13800, stock = 6, description = 'Touring motorcycle.' },
        { model = 'bati', price = 15000, financingPrice = 17250, stock = 6, description = 'Superbike standard.' },
        { model = 'bati2', price = 18000, financingPrice = 20700, stock = 5, description = 'Custom superbike.' },
        { model = 'bf400', price = 10000, financingPrice = 11500, stock = 7, description = 'Dirt bike.' },
        { model = 'carbonrs', price = 18000, financingPrice = 20700, stock = 5, description = 'Sport tourer.' },
        { model = 'cliffhanger', price = 15000, financingPrice = 17250, stock = 5, description = 'Chopper.' },
        { model = 'daemon', price = 12000, financingPrice = 13800, stock = 6, description = 'Classic chopper.' },
        { model = 'daemon2', price = 18000, financingPrice = 20700, stock = 5, description = 'Custom chopper.' },
        { model = 'defiler', price = 22000, financingPrice = 25300, stock = 4, description = 'Sport bike.' },
        { model = 'diablous', price = 15000, financingPrice = 17250, stock = 5, description = 'Custom cruiser.' },
        { model = 'diablous2', price = 20000, financingPrice = 23000, stock = 4, description = 'Custom cruiser.' },
        { model = 'double', price = 22000, financingPrice = 25300, stock = 4, description = 'Sport superbike.' },
        { model = 'enduro', price = 8000, financingPrice = 9200, stock = 7, description = 'Dual-sport motorcycle.' },
        { model = 'esskey', price = 15000, financingPrice = 17250, stock = 5, description = 'Retro cafe racer.' },
        { model = 'faggio', price = 3000, financingPrice = 3450, stock = 10, description = 'Scooter.' },
        { model = 'faggio2', price = 4000, financingPrice = 4600, stock = 8, description = 'Sport scooter.' },
        { model = 'faggio3', price = 5000, financingPrice = 5750, stock = 8, description = 'Custom scooter.' },
        { model = 'gargoyle', price = 18000, financingPrice = 20700, stock = 5, description = 'Chopper.' },
        { model = 'hakuchou', price = 25000, financingPrice = 28750, stock = 4, description = 'Sport superbike.' },
        { model = 'hakuchou2', price = 32000, financingPrice = 36800, stock = 3, description = 'Drag bike.' },
        { model = 'hexer', price = 12000, financingPrice = 13800, stock = 6, description = 'Chopper.' },
        { model = 'innovation', price = 18000, financingPrice = 20700, stock = 5, description = 'Custom chopper.' },
        { model = 'lectro', price = 22000, financingPrice = 25300, stock = 4, description = 'Electric sport bike.' },
        { model = 'manchez', price = 12000, financingPrice = 13800, stock = 6, description = 'Dirt bike.' },
        { model = 'manchez2', price = 18000, financingPrice = 20700, stock = 5, description = 'Custom dirt bike.' },
        { model = 'nemesis', price = 15000, financingPrice = 17250, stock = 5, description = 'Sport bike.' },
        { model = 'nightblade', price = 22000, financingPrice = 25300, stock = 4, description = 'Custom cruiser.' },
        { model = 'oracle', price = 42000, financingPrice = 48300, stock = 5, description = 'Executive luxury coupe.' },
        { model = 'pcj', price = 12000, financingPrice = 13800, stock = 6, description = 'Sport motorcycle.' },
        { model = 'ratbike', price = 6000, financingPrice = 6900, stock = 8, description = 'Rat bike.' },
        { model = 'ruffian', price = 15000, financingPrice = 17250, stock = 5, description = 'Street bike.' },
        { model = 'sanctus', price = 28000, financingPrice = 32200, stock = 3, description = 'Custom cruiser.' },
        { model = 'sovereign', price = 15000, financingPrice = 17250, stock = 5, description = 'Cruiser motorcycle.' },
        { model = 'thrust', price = 20000, financingPrice = 23000, stock = 4, description = 'Sport bike.' },
        { model = 'vader', price = 12000, financingPrice = 13800, stock = 6, description = 'Street bike.' },
        { model = 'vindicator', price = 22000, financingPrice = 25300, stock = 4, description = 'Sport tourer.' },
        { model = 'vortex', price = 18000, financingPrice = 20700, stock = 5, description = 'Sport bike.' },
        { model = 'wolfsbane', price = 12000, financingPrice = 13800, stock = 6, description = 'Chopper.' },
        { model = 'zombiea', price = 15000, financingPrice = 17250, stock = 5, description = 'Chopper.' },
        { model = 'zombieb', price = 18000, financingPrice = 20700, stock = 5, description = 'Custom chopper.' }
    },
    planes = {
        { model = 'besra', price = 350000, financingPrice = 402500, stock = 2, description = 'Jet trainer.' },
        { model = 'cuban800', price = 85000, financingPrice = 97750, stock = 4, description = 'Light utility aircraft.' },
        { model = 'duster', price = 55000, financingPrice = 63250, stock = 4, description = 'Crop duster.' },
        { model = 'howard', price = 180000, financingPrice = 207000, stock = 2, description = 'Classic stunt plane.' },
        { model = 'luxor', price = 450000, financingPrice = 517500, stock = 1, description = 'Luxury jet.' },
        { model = 'luxor2', price = 550000, financingPrice = 632500, stock = 1, description = 'Gold luxury jet.' },
        { model = 'mammatus', price = 95000, financingPrice = 109250, stock = 3, description = 'Light twin-engine.' },
        { model = 'miljet', price = 380000, financingPrice = 437000, stock = 1, description = 'Military transport.' },
        { model = 'nimbus', price = 480000, financingPrice = 552000, stock = 1, description = 'Executive jet.' },
        { model = 'shamal', price = 420000, financingPrice = 483000, stock = 1, description = 'Business jet.' },
        { model = 'velum', price = 75000, financingPrice = 86250, stock = 3, description = 'Light aircraft.' },
        { model = 'velum2', price = 95000, financingPrice = 109250, stock = 2, description = 'Modified light aircraft.' },
        { model = 'vestra', price = 280000, financingPrice = 322000, stock = 2, description = 'Sport aircraft.' }
    },
    helicopters = {
        { model = 'buzzard', price = 350000, financingPrice = 402500, stock = 2, description = 'Attack helicopter.' },
        { model = 'frogger', price = 150000, financingPrice = 172500, stock = 3, description = 'Utility helicopter.' },
        { model = 'frogger2', price = 180000, financingPrice = 207000, stock = 2, description = 'Custom utility heli.' },
        { model = 'havok', price = 120000, financingPrice = 138000, stock = 3, description = 'Light helicopter.' },
        { model = 'maverick', price = 95000, financingPrice = 109250, stock = 4, description = 'Civilian helicopter.' },
        { model = 'maverick2', price = 120000, financingPrice = 138000, stock = 3, description = 'Police helicopter.' },
        { model = 'seasparrow', price = 130000, financingPrice = 149500, stock = 2, description = 'Float-equipped helicopter.' },
        { model = 'skylift', price = 550000, financingPrice = 632500, stock = 1, description = 'Heavy lift helicopter.' },
        { model = 'supervolito', price = 250000, financingPrice = 287500, stock = 2, description = 'Luxury helicopter.' },
        { model = 'supervolito2', price = 280000, financingPrice = 322000, stock = 1, description = 'Executive helicopter.' },
        { model = 'swift', price = 220000, financingPrice = 253000, stock = 2, description = 'Sleek helicopter.' },
        { model = 'swift2', price = 280000, financingPrice = 322000, stock = 1, description = 'Custom sleek heli.' },
        { model = 'volatus', price = 320000, financingPrice = 368000, stock = 1, description = 'Ultra-luxury helicopter.' }
    },
    boats = {
        { model = 'dinghy', price = 25000, financingPrice = 28750, stock = 5, description = 'Small inflatable boat.' },
        { model = 'dinghy2', price = 30000, financingPrice = 34500, stock = 4, description = 'Military inflatable.' },
        { model = 'jetmax', price = 45000, financingPrice = 51750, stock = 4, description = 'Speedboat.' },
        { model = 'marquis', price = 85000, financingPrice = 97750, stock = 3, description = 'Luxury yacht tender.' },
        { model = 'seashark', price = 15000, financingPrice = 17250, stock = 5, description = 'Jet ski.' },
        { model = 'seashark2', price = 18000, financingPrice = 20700, stock = 4, description = 'Custom jet ski.' },
        { model = 'seashark3', price = 20000, financingPrice = 23000, stock = 4, description = 'Luxury jet ski.' },
        { model = 'speeder', price = 55000, financingPrice = 63250, stock = 3, description = 'Luxury speedboat.' },
        { model = 'speeder2', price = 65000, financingPrice = 74750, stock = 2, description = 'Custom luxury speedboat.' },
        { model = 'squalo', price = 35000, financingPrice = 40250, stock = 4, description = 'Sport boat.' },
        { model = 'suntrap', price = 28000, financingPrice = 32200, stock = 4, description = 'Leisure boat.' },
        { model = 'toro', price = 75000, financingPrice = 86250, stock = 2, description = 'Luxury speedboat.' },
        { model = 'toro2', price = 85000, financingPrice = 97750, stock = 2, description = 'Custom luxury speedboat.' },
        { model = 'tropic', price = 32000, financingPrice = 36800, stock = 4, description = 'Party boat.' },
        { model = 'tropic2', price = 42000, financingPrice = 48300, stock = 3, description = 'Custom party boat.' }
    }
}
