Config = Config or {}
Config.PremiumDealership = Config.PremiumDealership or {}

Config.PremiumDealership = {
    Locations = {
        Rockford = {
            coords = vector3(-870.0, -1080.0, 8.0),
            label = 'Rockford Luxury Motors',
            category = 'luxury',
            spawn = { coords = vector3(-865.0, -1075.0, 8.0), heading = 140.0 },
            showcase = { coords = vector3(-870.0, -1080.0, 8.0), heading = 140.0 },
        },
        Airport = {
            coords = vector3(-1030.0, -2720.0, 14.0),
            label = 'Airport Sports Garage',
            category = 'sports',
            spawn = { coords = vector3(-1025.0, -2715.0, 14.0), heading = 90.0 },
            showcase = { coords = vector3(-1030.0, -2720.0, 14.0), heading = 90.0 },
        },
        MirrorPark = {
            coords = vector3(1010.0, -650.0, 58.0),
            label = 'Mirror Park Auto Sales',
            category = 'normal',
            spawn = { coords = vector3(1015.0, -645.0, 58.0), heading = 0.0 },
            showcase = { coords = vector3(1010.0, -650.0, 58.0), heading = 0.0 },
        },
    },

    Categories = {
        luxury = {
            label = 'Luxury',
            description = 'Premium executive vehicles',
            color = '#FFD700',
            vehicles = {
                { model = 'paragon', label = 'Paragon R', price = 250000, speed = 200, seats = 4, image = 'paragon.png' },
                { model = 'superd', label = 'Super Diamond', price = 350000, speed = 185, seats = 4, image = 'superd.png' },
                { model = 'cog55', label = 'Cognoscenti 55', price = 280000, speed = 190, seats = 4, image = 'cog55.png' },
                { model = 'windsor', label = 'Windsor', price = 400000, speed = 195, seats = 2, image = 'windsor.png' },
                { model = 'stafford', label = 'Stafford', price = 320000, speed = 180, seats = 4, image = 'stafford.png' },
                { model = 'zion2', label = 'Zion Classic', price = 275000, speed = 200, seats = 2, image = 'zion2.png' },
                { model = 'fagaloa', label = 'Fagaloa', price = 220000, speed = 170, seats = 4, image = 'fagaloa.png' },
                { model = 'michelli', label = 'Michelli GT', price = 380000, speed = 210, seats = 2, image = 'michelli.png' },
                { model = 'bevo', label = 'G-Wagon', price = 350000, speed = 195, seats = 4, image = 'bevo.png' },
                { model = 'tolrrmansory', label = 'Rolls Royce Mansory', price = 500000, speed = 200, seats = 4, image = 'tolrrmansory.png' },
                { model = 'tolraptorV2', label = 'Ford Raptor V2', price = 320000, speed = 190, seats = 4, image = 'tolraptorV2.png' },
                { model = 'tolm6x6', label = 'Mercedes 6x6', price = 450000, speed = 175, seats = 6, image = 'tolm6x6.png' },
                { model = 'tolmm6x6', label = 'Mansory 6x6', price = 480000, speed = 180, seats = 6, image = 'tolmm6x6.png' },
            }
        },
        sports = {
            label = 'Sports',
            description = 'High-performance machines',
            color = '#FF4444',
            vehicles = {
                { model = 'nero', label = 'Nero', price = 550000, speed = 230, seats = 2, image = 'nero.png' },
                { model = 'pfister811', label = 'Pfister 811', price = 600000, speed = 240, seats = 2, image = 'pfister811.png' },
                { model = 'vagner', label = 'Vagner', price = 500000, speed = 235, seats = 2, image = 'vagner.png' },
                { model = 'gp1', label = 'GP1', price = 450000, speed = 225, seats = 2, image = 'gp1.png' },
                { model = 'infernus2', label = 'Infernus Classic', price = 420000, speed = 220, seats = 2, image = 'infernus2.png' },
                { model = 'turismor', label = 'Turismo R', price = 480000, speed = 230, seats = 2, image = 'turismor.png' },
                { model = 'tyrus', label = 'Tyrus', price = 520000, speed = 235, seats = 2, image = 'tyrus.png' },
                { model = 'prototipo', label = 'X80 Proto', price = 700000, speed = 250, seats = 2, image = 'prototipo.png' },
                { model = 'tolfxxk', label = 'Ferrari FXX-K Evo', price = 650000, speed = 245, seats = 2, image = 'tolfxxk.png' },
                { model = 'tolf8spider', label = 'Ferrari F8 Spider', price = 550000, speed = 235, seats = 2, image = 'tolf8spider.png' },
                { model = 'tolevo9', label = 'Lamborghini Evo 9', price = 500000, speed = 240, seats = 2, image = 'tolevo9.png' },
                { model = 'tolev36', label = 'Lamborghini Evo 36', price = 480000, speed = 235, seats = 2, image = 'tolev36.png' },
                { model = 'tolr8v10', label = 'Audi R8 V10', price = 450000, speed = 230, seats = 2, image = 'tolr8v10.png' },
                { model = 'tolr8c', label = 'Audi R8 C', price = 430000, speed = 225, seats = 2, image = 'tolr8c.png' },
                { model = 'tolf360', label = 'Ferrari F360', price = 420000, speed = 225, seats = 2, image = 'tolf360.png' },
                { model = 'tollam2', label = 'Lamborghini', price = 500000, speed = 240, seats = 2, image = 'tollam2.png' },
                { model = 'tolgtam21', label = 'GT AM21', price = 600000, speed = 245, seats = 2, image = 'tolgtam21.png' },
            }
        },
        normal = {
            label = 'Normal',
            description = 'Everyday reliable vehicles',
            color = '#4488FF',
            vehicles = {
                { model = 'exemplar', label = 'Exemplar', price = 95000, speed = 185, seats = 4, image = 'exemplar.png' },
                { model = 'felon2', label = 'Felon GT', price = 85000, speed = 180, seats = 4, image = 'felon2.png' },
                { model = 'jackal', label = 'Jackal', price = 75000, speed = 175, seats = 4, image = 'jackal.png' },
                { model = 'oracle2', label = 'Oracle', price = 70000, speed = 170, seats = 4, image = 'oracle2.png' },
                { model = 'sentinel2', label = 'Sentinel XS', price = 65000, speed = 180, seats = 2, image = 'sentinel2.png' },
                { model = 'surge', label = 'Surge', price = 55000, speed = 165, seats = 4, image = 'surge.png' },
                { model = 'tailgater', label = 'Tailgater', price = 60000, speed = 170, seats = 4, image = 'tailgater.png' },
                { model = 'premier', label = 'Premier', price = 45000, speed = 160, seats = 4, image = 'premier.png' },
                { model = 'tol22m5', label = 'BMW M22', price = 95000, speed = 190, seats = 4, image = 'tol22m5.png' },
                { model = 'tol240sx', label = 'Nissan 240SX', price = 55000, speed = 175, seats = 2, image = 'tol240sx.png' },
                { model = 'tol3j50', label = 'TOL 3J50', price = 65000, speed = 180, seats = 2, image = 'tol3j50.png' },
                { model = 'tol675ltsp', label = 'TOL 675 LTSP', price = 85000, speed = 190, seats = 2, image = 'tol675ltsp.png' },
                { model = 'tol700', label = 'TOL 700', price = 70000, speed = 185, seats = 4, image = 'tol700.png' },
                { model = 'tola6', label = 'Audi A6', price = 75000, speed = 185, seats = 4, image = 'tola6.png' },
                { model = 'tolap2', label = 'TOL AP2', price = 65000, speed = 180, seats = 2, image = 'tolap2.png' },
                { model = 'tolaudidy', label = 'Audi DY', price = 80000, speed = 190, seats = 4, image = 'tolaudidy.png' },
                { model = 'tolbt62r', label = 'Brabus 62R', price = 120000, speed = 200, seats = 4, image = 'tolbt62r.png' },
                { model = 'tolc63', label = 'AMG C63', price = 85000, speed = 195, seats = 4, image = 'tolc63.png' },
                { model = 'tolc7', label = 'Corvette C7', price = 95000, speed = 205, seats = 2, image = 'tolc7.png' },
                { model = 'tolcharger2', label = 'Dodge Charger', price = 70000, speed = 190, seats = 4, image = 'tolcharger2.png' },
                { model = 'tolcurus', label = 'TOL Curus', price = 65000, speed = 175, seats = 4, image = 'tolcurus.png' },
                { model = 'toldemon', label = 'Dodge Demon', price = 110000, speed = 210, seats = 2, image = 'toldemon.png' },
                { model = 'toldurus', label = 'Dodge Durango', price = 65000, speed = 180, seats = 6, image = 'toldurus.png' },
                { model = 'tole36prb', label = 'BMW E36', price = 50000, speed = 175, seats = 4, image = 'tole36prb.png' },
                { model = 'tole36v', label = 'BMW E36 V', price = 55000, speed = 180, seats = 4, image = 'tole36v.png' },
                { model = 'tole6314', label = 'BMW E63 M6', price = 75000, speed = 195, seats = 4, image = 'tole6314.png' },
                { model = 'tolexor', label = 'Lexus', price = 70000, speed = 185, seats = 4, image = 'tolexor.png' },
                { model = 'tolka', label = 'Kia', price = 35000, speed = 165, seats = 4, image = 'tolka.png' },
                { model = 'tollwalk458', label = 'TOL LW458', price = 85000, speed = 195, seats = 2, image = 'tollwalk458.png' },
                { model = 'tolm5cs22', label = 'BMW M5 CS', price = 95000, speed = 200, seats = 4, image = 'tolm5cs22.png' },
                { model = 'tolm5e60', label = 'BMW M5 E60', price = 80000, speed = 195, seats = 4, image = 'tolm5e60.png' },
                { model = 'tolmig', label = 'TOL MiG', price = 60000, speed = 185, seats = 2, image = 'tolmig.png' },
                { model = 'tolmus2', label = 'TOL Mustang', price = 65000, speed = 190, seats = 2, image = 'tolmus2.png' },
                { model = 'tolmustan', label = 'Mustang', price = 65000, speed = 190, seats = 2, image = 'tolmustan.png' },
                { model = 'tolmustang', label = 'Mustang GT', price = 70000, speed = 195, seats = 4, image = 'tolmustang.png' },
                { model = 'tolpeigerzen', label = 'Peiger Zen', price = 55000, speed = 180, seats = 2, image = 'tolpeigerzen.png' },
                { model = 'tolr33', label = 'Nissan Skyline R33', price = 80000, speed = 195, seats = 4, image = 'tolr33.png' },
                { model = 'tolraid', label = 'TOL Raid', price = 60000, speed = 180, seats = 4, image = 'tolraid.png' },
                { model = 'tolrs5', label = 'Audi RS5', price = 85000, speed = 200, seats = 4, image = 'tolrs5.png' },
                { model = 'tolrs6', label = 'Audi RS6', price = 95000, speed = 205, seats = 4, image = 'tolrs6.png' },
                { model = 'tolrs7c821', label = 'Audi RS7', price = 100000, speed = 205, seats = 4, image = 'tolrs7c821.png' },
                { model = 'tolrsurus', label = 'RS Urus', price = 110000, speed = 200, seats = 4, image = 'tolrsurus.png' },
                { model = 'tols63amg', label = 'AMG S63', price = 100000, speed = 205, seats = 4, image = 'tols63amg.png' },
            }
        },
    },

    TestDriveDuration = 120,
    TradeInMultiplier = 0.65,
    PlateMaxLength = 8,
    FinanceOptions = { 4, 8, 12 },
    FinanceInterestRate = 1.05,
}
