Config = Config or {}

Config.Emotes = {
    Dances = {
        { name = 'Dance A', dict = 'mp_player_int_upperdance', anim = 'mp_player_int_dance_a', duration = -1 },
        { name = 'Dance B', dict = 'mp_player_int_upperdance', anim = 'mp_player_int_dance_b', duration = -1 },
        { name = 'Dance C', dict = 'mp_player_int_upperdance', anim = 'mp_player_int_dance_c', duration = -1 },
        { name = 'Dance D', dict = 'mp_player_int_upperdance', anim = 'mp_player_int_dance_d', duration = -1 },
        { name = 'Dance E', dict = 'mp_player_int_upperdance', anim = 'mp_player_int_dance_e', duration = -1 },
        { name = 'Dance F', dict = 'mp_player_int_upperdance', anim = 'mp_player_int_dance_f', duration = -1 },
        { name = 'Dance G', dict = 'mp_player_int_upperdance', anim = 'mp_player_int_dance_g', duration = -1 },
        { name = 'Dance H', dict = 'mp_player_int_upperdance', anim = 'mp_player_int_dance_h', duration = -1 },
        { name = 'Dance I', dict = 'mp_player_int_upperdance', anim = 'mp_player_int_dance_i', duration = -1 },
        { name = 'Dance J', dict = 'mp_player_int_upperdance', anim = 'mp_player_int_dance_j', duration = -1 },
        { name = 'Shuffle', dict = 'anim@amb@nightclub@dancers@crowddance_groups@', anim = 'hi_dance_bhangra_01_v2', duration = -1 },
        { name = 'Electro', dict = 'anim@amb@nightclub@dancers@crowddance_groups@', anim = 'hi_dance_elec_01_v2', duration = -1 },
        { name = 'Step Up', dict = 'anim@amb@nightclub@dancers@crowddance_groups@', anim = 'hi_dance_step_01_v2', duration = -1 },
        { name = 'Pop Lock', dict = 'anim@amb@nightclub@dancers@crowddance_groups@', anim = 'hi_dance_pop_01_v2', duration = -1 },
        { name = 'Salsa', dict = 'anim@amb@nightclub@dancers@crowddance_groups@', anim = 'hi_dance_salsa_01_v2', duration = -1 },
        { name = 'Slow Dance', dict = 'anim@amb@nightclub@dancers@crowddance_groups@', anim = 'hi_dance_slow_01_v2', duration = -1 },
        { name = 'Street Dance', dict = 'anim@amb@nightclub@dancers@crowddance_groups@', anim = 'hi_dance_street_01_v2', duration = -1 },
        { name = 'Club Groove', dict = 'anim@amb@nightclub@dancers@crowddance_groups@', anim = 'hi_dance_groove_01_v2', duration = -1 },
        { name = 'Dixie', dict = 'timetable@reunited@ig_10', anim = 'dixie_ride', duration = -1 },
        { name = 'Shuffle Dance', dict = 'anim@amb@nightclub@dancers@crowddance_groups@', anim = 'hi_dance_shuffle_01_v2', duration = -1 },
        { name = 'Pogo', dict = 'anim@amb@nightclub@dancers@crowddance_groups@', anim = 'hi_dance_pogo_01_v2', duration = -1 },
        { name = 'Club Classic', dict = 'anim@amb@nightclub@dancers@crowddance_groups@', anim = 'hi_dance_classic_01_v2', duration = -1 },
        { name = 'Freestyle', dict = 'anim@amb@nightclub@dancers@crowddance_groups@', anim = 'hi_dance_freestyle_01_v2', duration = -1 },
        { name = 'Hip Hop', dict = 'anim@amb@nightclub@dancers@crowddance_groups@', anim = 'hi_dance_hiphop_01_v2', duration = -1 }
    },
    Gestures = {
        { name = 'Point', dict = 'gestures@m@standing@casual', anim = 'gesture_point', duration = 2000 },
        { name = 'Hello', dict = 'gestures@m@standing@casual', anim = 'gesture_hello', duration = 2000 },
        { name = 'Hands Up', dict = 'missminuteman_1ig_2', anim = 'handsup_base', duration = -1 },
        { name = 'Middle Finger', dict = 'mp_player_int_uppergesture', anim = 'mp_player_int_gesture_middle_finger', duration = 3000 },
        { name = 'Thumb Down', dict = 'mp_player_int_uppergesture', anim = 'mp_player_int_gesture_thumb_down', duration = 2000 },
        { name = 'Thumb Up', dict = 'mp_player_int_uppergesture', anim = 'mp_player_int_gesture_thumb_up', duration = 2000 },
        { name = 'Nod Yes', dict = 'mp_player_int_uppergesture', anim = 'mp_player_int_gesture_nod_yes', duration = 1500 },
        { name = 'Shake No', dict = 'mp_player_int_uppergesture', anim = 'mp_player_int_gesture_shake_head_no', duration = 1500 },
        { name = 'Shrug', dict = 'gestures@m@standing@casual', anim = 'gesture_shrug', duration = 2000 },
        { name = 'OK', dict = 'mp_player_int_uppergesture', anim = 'mp_player_int_gesture_ok', duration = 2000 },
        { name = 'Come Here', dict = 'mp_player_int_uppergesture', anim = 'mp_player_int_gesture_come_here', duration = 2000 },
        { name = 'What', dict = 'gestures@m@standing@casual', anim = 'gesture_what', duration = 2000 },
        { name = 'Me', dict = 'gestures@m@standing@casual', anim = 'gesture_me', duration = 1500 },
        { name = 'Talk to Hand', dict = 'mp_player_int_uppergesture', anim = 'mp_player_int_gesture_talk_to_hand', duration = 2000 },
        { name = 'Facepalm', dict = 'anim@mp_player_intcelebrationmale@face_palm', anim = 'face_palm', duration = 2500 },
        { name = 'Salute', dict = 'mp_player_int_uppergesture', anim = 'mp_player_int_gesture_salute', duration = 2000 }
    },
    Idles = {
        { name = 'Lean Against Wall', dict = 'amb@world_human_leaning@male@wall@back@legs_crossed@base', anim = 'base', duration = -1 },
        { name = 'Lean Against Car', dict = 'amb@world_human_leaning@male@car@biker@base', anim = 'base', duration = -1 },
        { name = 'Arms Crossed', dict = 'amb@world_human_hang_out_street@male_b@base', anim = 'base', duration = -1 },
        { name = 'Wait Lean', dict = 'amb@world_human_lean_male@wall@back@legs_crossed@idle_a', anim = 'idle_a', duration = -1 },
        { name = 'Smoke Cigarette', dict = 'amb@world_human_smoking@male@male_a@base', anim = 'base', duration = -1 },
        { name = 'Hold Cigarette', dict = 'amb@world_human_stand_impatient@male@no_sign@base', anim = 'base', duration = -1 },
        { name = 'Check Phone', dict = 'cellphone@', anim = 'cellphone_text_in', duration = -1 },
        { name = 'Look Around', dict = 'missfinale_c2@', anim = 'idle_camper', duration = -1 },
        { name = 'Hands Behind Back', dict = 'rcmnigel1cnmt_16b', anim = 'idle_hand_on_rail', duration = -1 },
        { name = 'Lean On Counter', dict = 'amb@world_human_leaning@male@counter@base', anim = 'base', duration = -1 },
        { name = 'Standing Guard', dict = 'anim@heists@prison_heiststation@guard', anim = 'idle', duration = -1 },
        { name = 'Cross Arms Look', dict = 'amb@world_human_hang_out_street@female_arm_crossed@base', anim = 'base', duration = -1 },
        { name = 'Impatient', dict = 'amb@world_human_stand_impatient@male@no_sign@base', anim = 'base', duration = -1 },
        { name = 'Relax', dict = 'amb@world_human_stand_fire@male@idle_b', anim = 'idle_b', duration = -1 },
        { name = 'Stance A', dict = 'amb@world_human_stand_stripclub@male@idle_a', anim = 'idle_a', duration = -1 },
        { name = 'Stance B', dict = 'amb@world_human_stand_stripclub@male@idle_b', anim = 'idle_b', duration = -1 },
        { name = 'Stance C', dict = 'amb@world_human_stand_stripclub@male@idle_c', anim = 'idle_c', duration = -1 }
    },
    Expressions = {
        { name = 'Angry', dict = 'mp_player_int_upperexpression', anim = 'mp_player_int_gesture_angry', duration = 3000 },
        { name = 'Blow Kiss', dict = 'mp_player_int_upperexpression', anim = 'mp_player_int_gesture_blow_kiss', duration = 2500 },
        { name = 'Bow', dict = 'mp_player_int_upperexpression', anim = 'mp_player_int_gesture_bow', duration = 2500 },
        { name = 'Cry', dict = 'mp_player_int_upperexpression', anim = 'mp_player_int_gesture_cry', duration = 3000 },
        { name = 'Fear', dict = 'mp_player_int_upperexpression', anim = 'mp_player_int_gesture_fear', duration = 2000 },
        { name = 'Jealous', dict = 'mp_player_int_upperexpression', anim = 'mp_player_int_gesture_jealous', duration = 2000 },
        { name = 'Sad', dict = 'mp_player_int_upperexpression', anim = 'mp_player_int_gesture_sad', duration = 2500 },
        { name = 'Surprise', dict = 'mp_player_int_upperexpression', anim = 'mp_player_int_gesture_surprise', duration = 2000 },
        { name = 'Worship', dict = 'mp_player_int_upperexpression', anim = 'mp_player_int_gesture_worship', duration = 2500 },
        { name = 'Laugh', dict = 'anim@mp_player_intcelebrationmale@laugh', anim = 'laugh', duration = 3000 },
        { name = 'Shock', dict = 'anim@mp_player_intcelebrationmale@shock', anim = 'shock', duration = 2500 },
        { name = 'Wince', dict = 'anim@mp_player_intcelebrationmale@wince', anim = 'wince', duration = 2000 },
        { name = 'Cheer', dict = 'mp_player_int_upperexpression', anim = 'mp_player_int_gesture_cheer', duration = 3000 },
        { name = 'Clap', dict = 'mp_player_int_upperexpression', anim = 'mp_player_int_gesture_clap', duration = 3000 }
    },
    Greetings = {
        { name = 'Wave', dict = 'mp_player_int_uppergesture', anim = 'mp_player_int_gesture_wave', duration = 2500 },
        { name = 'Handshake', dict = 'mp_ped_interaction', anim = 'handshake_guy_a', duration = 3000 },
        { name = 'High Five', dict = 'mp_ped_interaction', anim = 'highfive_guy_a', duration = 2500 },
        { name = 'Hug', dict = 'mp_ped_interaction', anim = 'hug_guy_a', duration = 3000 },
        { name = 'Bodyguard Hug', dict = 'mp_ped_interaction', anim = 'hug_guy_b', duration = 3000 },
        { name = 'Salute Army', dict = 'mp_player_int_uppergesture', anim = 'mp_player_int_gesture_salute', duration = 2000 },
        { name = 'Bow Greet', dict = 'mp_player_int_upperexpression', anim = 'mp_player_int_gesture_bow', duration = 2000 },
        { name = 'Kiss Cheek', dict = 'mp_ped_interaction', anim = 'kiss_guy_a', duration = 2500 },
        { name = 'Fist Bump', dict = 'mp_ped_interaction', anim = 'fist_bump_a', duration = 2000 },
        { name = 'Gang Handshake', dict = 'mp_ped_interaction', anim = 'handshake_guy_b', duration = 3000 }
    },
    Actions = {
        { name = 'Sit Ground', dict = 'amb@world_human_sunbathe@male@back@base', anim = 'base', duration = -1 },
        { name = 'Sit Chair', dict = 'anim@heists@fleeca_bank@seated_idles', anim = 'idle_c', duration = -1 },
        { name = 'Lay Down', dict = 'amb@world_human_sunbathe@male@back@base', anim = 'base', duration = -1 },
        { name = 'Push Ups', dict = 'amb@world_human_push_ups@male@idle_a', anim = 'idle_a', duration = -1 },
        { name = 'Sit Ups', dict = 'amb@world_human_sit_ups@male@idle_a', anim = 'idle_a', duration = -1 },
        { name = 'Yoga', dict = 'amb@world_human_yoga@male@base', anim = 'base', duration = -1 },
        { name = 'Meditate', dict = 'amb@world_human_stand_fire@male@idle_b', anim = 'idle_b', duration = -1 },
        { name = 'Kneel', dict = 'amb@world_human_picnic@male@idle', anim = 'idle', duration = -1 },
        { name = 'Pray', dict = 'amb@prop_human_movie_bulb@base', anim = 'base', duration = -1 },
        { name = 'Selfie', dict = 'mp_player_int_selfie', anim = 'idle_a', duration = -1 },
        { name = 'Lean Forward', dict = 'amb@code_human_in_car_mp_actions@lean@ds@base', anim = 'base', duration = -1 },
        { name = 'Drink', dict = 'mp_player_intdrink', anim = 'intro_bottle', duration = 3000 },
        { name = 'Eat Snack', dict = 'mp_player_inteat@pnq', anim = 'loop', duration = -1 },
        { name = 'Vomit', dict = 'missfbi4prepp1', anim = 'vomit', duration = 5000 },
        { name = 'Search', dict = 'missfbi4prepp1', anim = 'look_around', duration = -1 },
        { name = 'Clean', dict = 'timetable@floyd@clean_kitchen@base', anim = 'base', duration = -1 },
        { name = 'Fix Tool', dict = 'mini@repair', anim = 'fixing_a_ped', duration = -1 },
        { name = 'Fish', dict = 'amb@world_human_stand_fishing@base', anim = 'base', duration = -1 },
        { name = 'Golf Putt', dict = 'mini@golf', anim = 'putt_01', duration = 3000 },
        { name = 'Baseball Swing', dict = 'mini@baseball', anim = 'bat_swing', duration = 2000 },
        { name = 'Tennis Swing', dict = 'mini@tennis', anim = 'forehand_ts_hard', duration = 2000 },
        { name = 'Boxing Jab', dict = 'mini@boxing', anim = 'jab', duration = 1500 },
        { name = 'Boxing Uppercut', dict = 'mini@boxing', anim = 'uppercut', duration = 1500 },
        { name = 'Kick Ground', dict = 'amb@world_human_gardener@male@base', anim = 'base', duration = -1 },
        { name = 'Carry Box', dict = 'anim@heists@box_carry@', anim = 'idle', duration = -1 },
        { name = 'Pickup Object', dict = 'random@domestic', anim = 'pickup_low', duration = 2000 }
    },
    Miscellaneous = {
        { name = 'Chill', dict = 'amb@world_human_stripedivider@male@base', anim = 'base', duration = -1 },
        { name = 'Guard Rail', dict = 'amb@world_human_lean_male@rail@base', anim = 'base', duration = -1 },
        { name = 'Photos', dict = 'amb@world_human_mobile_film@base', anim = 'base', duration = -1 },
        { name = 'Binoculars', dict = 'amb@world_human_binoculars@male@base', anim = 'base', duration = -1 },
        { name = 'Clipboard', dict = 'missfbi4prepp1', anim = 'idle_clipboard', duration = -1 },
        { name = 'Drilling', dict = 'mini@drilling', anim = 'drill_strike', duration = -1 },
        { name = 'Welding', dict = 'amb@world_human_welding@male@base', anim = 'base', duration = -1 },
        { name = 'Guitar', dict = 'amb@world_human_musician@guitar@male@idle_a', anim = 'idle_a', duration = -1 },
        { name = 'Bongos', dict = 'amb@world_human_musician@congas@male@idle_a', anim = 'idle_a', duration = -1 },
        { name = 'DJ Scratch', dict = 'anim@mp_player_intcelebrationmale@dj', anim = 'dj', duration = -1 },
        { name = 'Play Cards', dict = 'amb@world_human_playing_cards@male@base', anim = 'base', duration = -1 },
        { name = 'Typewriter', dict = 'anim@heists@prison_heiststation@typewriter', anim = 'typewriter', duration = -1 },
        { name = 'Book Read', dict = 'amb@world_human_seat_wall_table@male@base', anim = 'base', duration = -1 },
        { name = 'Newspaper', dict = 'missfbi4prepp1', anim = 'idle_newspaper', duration = -1 },
        { name = 'Crowd Control', dict = 'amb@world_human_crowd_control@male@base', anim = 'base', duration = -1 },
        { name = 'Guard Patrol', dict = 'amb@world_human_guard_patrol@male@idle_a', anim = 'idle_a', duration = -1 },
        { name = 'Stretch', dict = 'amb@world_human_stretch@male@idle_a', anim = 'idle_a', duration = 4000 },
        { name = 'Window Shop', dict = 'amb@world_human_window_shop@male@base', anim = 'base', duration = -1 },
        { name = 'Queue Wait', dict = 'amb@world_human_queue@male@base', anim = 'base', duration = -1 },
        { name = 'Statue Pose', dict = 'amb@world_human_statue@male@base', anim = 'base', duration = -1 }
    }
}

Config.EmoteKeybind = 'U'
Config.EmoteOpenCommand = 'anim'
Config.EmoteOpenCommandAlt = 'e'
Config.CancelEmoteKey = 'X'
Config.EnableRagdollCancel = true
