Config = Config or {}
Config.FoodTruck = {
    trucks = {
        {
            id = 'taco_truck',
            name = 'Taco Truck',
            model = 'taco',
            price = 150000,
            coords = vector3(118.0, -1280.0, 29.0),
            spawn = vector3(118.0, -1280.0, 29.0),
        },
        {
            id = 'burger_truck',
            name = 'Burger Truck',
            model = 'pizza',
            price = 200000,
            coords = vector3(-1200.0, -900.0, 14.0),
            spawn = vector3(-1200.0, -900.0, 14.0),
        },
        {
            id = 'icecream_truck',
            name = 'Ice Cream Truck',
            model = 'ice',
            price = 180000,
            coords = vector3(810.0, -550.0, 27.0),
            spawn = vector3(810.0, -550.0, 27.0),
        },
    },
    menuItems = {
        { id = 'taco', name = 'Taco', price = 25, ingredients = { { item = 'meat', qty = 1 }, { item = 'tortilla', qty = 1 }, { item = 'lettuce', qty = 1 } }, cookTime = 5000 },
        { id = 'burger', name = 'Burger', price = 35, ingredients = { { item = 'meat', qty = 1 }, { item = 'bread', qty = 2 }, { item = 'lettuce', qty = 1 } }, cookTime = 7000 },
        { id = 'hotdog', name = 'Hot Dog', price = 20, ingredients = { { item = 'meat', qty = 1 }, { item = 'bread', qty = 1 } }, cookTime = 4000 },
        { id = 'fries', name = 'Fries', price = 15, ingredients = { { item = 'potato', qty = 2 } }, cookTime = 3000 },
        { id = 'soda', name = 'Soda', price = 10, ingredients = { { item = 'syrup', qty = 1 }, { item = 'water', qty = 1 } }, cookTime = 2000 },
        { id = 'icecream', name = 'Ice Cream Cone', price = 20, ingredients = { { item = 'cream', qty = 1 }, { item = 'sugar', qty = 1 } }, cookTime = 3000 },
        { id = 'taco_supreme', name = 'Taco Supreme', price = 40, ingredients = { { item = 'meat', qty = 2 }, { item = 'tortilla', qty = 1 }, { item = 'lettuce', qty = 1 }, { item = 'cheese', qty = 1 } }, cookTime = 8000 },
        { id = 'deluxe_burger', name = 'Deluxe Burger', price = 50, ingredients = { { item = 'meat', qty = 2 }, { item = 'bread', qty = 2 }, { item = 'cheese', qty = 1 }, { item = 'lettuce', qty = 1 } }, cookTime = 10000 },
    },
    ingredients = {
        meat = { label = 'Meat', price = 5 },
        bread = { label = 'Bread', price = 2 },
        tortilla = { label = 'Tortilla', price = 2 },
        lettuce = { label = 'Lettuce', price = 3 },
        cheese = { label = 'Cheese', price = 4 },
        tomato = { label = 'Tomato', price = 3 },
        potato = { label = 'Potato', price = 2 },
        syrup = { label = 'Syrup', price = 3 },
        cream = { label = 'Cream', price = 4 },
        sugar = { label = 'Sugar', price = 2 },
        water = { label = 'Water', price = 1 },
    },
    healthInspectionFee = 5000,
    deliveryRadius = 100.0,
    satisfactionDecay = 0.1,
    maxOrders = 5,
}
