Config = Config or {}

Config.Heists = {
    globalCooldown = 1800,
    policeAlertRange = 2000.0,
    requiredPolice = 3,
    lootValueMultiplier = 1.0,

    heists = {
        ['fleeca'] = {
            label = 'Fleeca Bank',
            description = 'Small bank heist — drill the vault, hack the terminal, grab the cash.',
            icon = 'building-columns',
            cooldown = 900,
            maxParticipants = 4,
            locations = {
                entry = vec3(147.0, -1040.0, 29.0),
                vault = vec3(150.5, -1045.5, 29.0),
                escape = vec3(147.0, -1055.0, 29.0),
            },
            phases = {
                { label = 'Drill Vault', time = 15000, item = 'drill', desc = 'Place the drill on the vault door' },
                { label = 'Hack Terminal', time = 20000, item = 'hack_usb', desc = 'Insert hack USB into security terminal' },
                { label = 'Grab Cash', time = 10000, item = nil, desc = 'Collect cash from the vault' },
            },
            requiredItems = { 'drill', 'hack_usb' },
            lootMin = 4,
            lootMax = 8,
            lootReward = { name = 'heist_loot', min = 50000, max = 100000, label = 'Cash Bundle' },
            policeAlertPhase = 1,
        },
        ['jewelry'] = {
            label = 'Jewelry Store',
            description = 'High-end jewelry heist — smash cases, grab loot, escape fast.',
            icon = 'gem',
            cooldown = 1200,
            maxParticipants = 4,
            locations = {
                entry = vec3(-630.0, -236.0, 38.0),
                vault = vec3(-632.0, -232.0, 38.0),
                escape = vec3(-620.0, -240.0, 38.0),
            },
            phases = {
                { label = 'Smash Display Cases', time = 8000, item = nil, desc = 'Break the display cases' },
                { label = 'Collect Jewelry', time = 15000, item = nil, desc = 'Grab jewelry from broken cases' },
                { label = 'Bag the Loot', time = 10000, item = nil, desc = 'Pack the jewelry into bags' },
            },
            requiredItems = {},
            lootMin = 6,
            lootMax = 12,
            lootReward = { name = 'heist_loot', min = 80000, max = 150000, label = 'Jewelry Bundle' },
            policeAlertPhase = 0,
            smashCount = 6,
            smashTimer = 120,
        },
        ['banktruck'] = {
            label = 'Bank Truck',
            description = 'Armored truck heist — intercept, breach, loot, and flee.',
            icon = 'truck',
            cooldown = 1500,
            maxParticipants = 5,
            spawnInterval = { min = 1800, max = 3600 },
            locations = {
                routes = {
                    { start = vec3(-1800.0, 300.0, 80.0), end = vec3(2000.0, 500.0, 80.0) },
                    { start = vec3(500.0, -2000.0, 20.0), end = vec3(500.0, 2000.0, 20.0) },
                    { start = vec3(-2000.0, 2000.0, 80.0), end = vec3(1000.0, 3000.0, 40.0) },
                },
            },
            phases = {
                { label = 'Stop the Truck', time = 5000, item = nil, desc = 'Force the truck to stop' },
                { label = 'Place C4', time = 5000, item = 'c4_charge', desc = 'Place explosive on truck door' },
                { label = 'Detonate & Loot', time = 8000, item = nil, desc = 'Detonate and grab the cash' },
            },
            requiredItems = { 'c4_charge' },
            lootMin = 5,
            lootMax = 10,
            lootReward = { name = 'heist_loot', min = 100000, max = 200000, label = 'Armored Cash' },
            policeAlertPhase = 0,
        },
        ['paleto'] = {
            label = 'Paleto Bay Bank',
            description = 'Major bank heist — cut power, drill the vault, defend against police.',
            icon = 'vault',
            cooldown = 2400,
            maxParticipants = 6,
            locations = {
                entry = vec3(-105.0, 6475.0, 31.0),
                vault = vec3(-103.5, 6471.0, 31.0),
                escape = vec3(-115.0, 6470.0, 31.0),
            },
            phases = {
                { label = 'Cut Power', time = 10000, item = nil, desc = 'Disable the bank\'s power supply' },
                { label = 'Drill Primary Vault', time = 30000, item = 'drill', desc = 'Drill through the main vault door' },
                { label = 'Drill Inner Vault', time = 25000, item = 'drill', desc = 'Drill the inner vault compartment' },
                { label = 'Hack Security Grid', time = 20000, item = 'hack_usb', desc = 'Bypass the security grid' },
                { label = 'Secure Loot', time = 15000, item = nil, desc = 'Collect the vault contents' },
                { label = 'Hold Off Police', time = 60000, item = nil, desc = 'Defend the position during escape prep' },
            },
            requiredItems = { 'drill', 'hack_usb', 'c4_charge' },
            lootMin = 10,
            lootMax = 20,
            lootReward = { name = 'heist_loot', min = 200000, max = 400000, label = 'Vault Contents' },
            policeAlertPhase = 0,
        },
    },
}
