Config = Config or {}

Config.Blacklist = {
    enabled = true,
    logAttempts = true,
    kickOnViolation = false,
    warningMessage = 'Model blocked by server administration.',
    checkInterval = 10000,
    adminAce = 'admin.blacklist'
}

Config.BlacklistedPeds = {
    ['a_m_m_afriamer_01'] = true,
    ['a_m_m_bevhills_01'] = true,
    ['u_m_m_jesus_01'] = true,
    ['csb_agent'] = true,
    ['csb_anton'] = true,
    ['csb_avon'] = true,
    ['csb_bogdan'] = true,
    ['csb_cheng'] = true,
    ['csb_chin_goon'] = true,
    ['csb_cliff'] = true,
    ['csb_col_casino'] = true,
    ['csb_cop'] = true,
    ['csb_customer'] = true,
    ['csb_dix'] = true,
    ['csb_dom'] = true,
    ['csb_drfriedlander'] = true,
    ['csb_englishman'] = true,
    ['csb_fosso'] = true,
    ['csb_g'] = true,
    ['csb_gustavo'] = true,
    ['csb_hugh'] = true,
    ['csb_isabela'] = true,
    ['csb_janitor'] = true,
    ['csb_maude'] = true,
    ['csb_miguel'] = true,
    ['csb_mimi'] = true,
    ['csb_money'] = true,
    ['csb_mp_agent14'] = true,
    ['csb_mweather'] = true,
    ['csb_old_man'] = true,
    ['csb_orleans'] = true,
    ['csb_oscar'] = true,
    ['csb_porndudes'] = true,
    ['csb_prologuedriver'] = true,
    ['csb_prologuemen'] = true,
    ['csb_prologuemoun'] = true,
    ['csb_prologuesat'] = true,
    ['csb_ramp_gang'] = true,
    ['csb_ramp_hic'] = true,
    ['csb_ramp_hipster'] = true,
    ['csb_ramp_marine'] = true,
    ['csb_ramp_mex'] = true,
    ['csb_reporter'] = true,
    ['csb_roccopelosi'] = true,
    ['csb_screen_writer'] = true,
    ['csb_siemon'] = true,
    ['csb_solomon'] = true,
    ['csb_stripper_01'] = true,
    ['csb_stripper_02'] = true,
    ['csb_talcc'] = true,
    ['csb_talmm'] = true,
    ['csb_taocook'] = true,
    ['csb_taostranslator'] = true,
    ['csb_tenniscoach'] = true,
    ['csb_terry'] = true,
    ['csb_tom'] = true,
    ['csb_tonya'] = true,
    ['csb_trafficwarden'] = true,
    ['csb_undercover'] = true,
    ['csb_vagspeak'] = true,
    ['csb_waiter'] = true,
    ['csb_weinstein'] = true,
    ['csb_wendy'] = true,
    ['csb_zimbor'] = true,
}

Config.BlacklistedVehicles = {
    ['rhino'] = true,
    ['cargobob3'] = true,
    ['cargobob4'] = true,
    ['buzzard2'] = true,
    ['annihilator'] = true,
    ['hydra'] = true,
    ['lazer'] = true,
    ['titan'] = true,
    ['valkyrie'] = true,
    ['valkyrie2'] = true,
    ['savage'] = true,
    ['skylift'] = true,
    ['cutter'] = true,
    ['dump'] = true,
    ['handler'] = true,
    ['riot'] = true,
    ['riot2'] = true,
    ['sheriff'] = true,
    ['sheriff2'] = true,
    ['pbus'] = true,
    ['pbus2'] = true,
    ['police'] = true,
    ['police2'] = true,
    ['police3'] = true,
    ['police4'] = true,
    ['police5'] = true,
    ['police6'] = true,
    ['policeold1'] = true,
    ['policeold2'] = true,
    ['polmav'] = true,
}

Config.BlacklistedWeapons = {
    ['weapon_railgun'] = true,
    ['weapon_rayminigun'] = true,
    ['weapon_minigun'] = true,
    ['weapon_rpg'] = true,
    ['weapon_hominglauncher'] = true,
    ['weapon_compactlauncher'] = true,
    ['weapon_grenadelauncher'] = true,
    ['weapon_stickybomb'] = true,
    ['weapon_proxmine'] = true,
    ['weapon_pipebomb'] = true,
    ['weapon_grenade'] = true,
    ['weapon_smokegrenade'] = true,
    ['weapon_flaregun'] = true,
    ['weapon_emplauncher'] = true,
    ['weapon_firework'] = true,
    ['weapon_musket'] = true,
}

Config.AllowedJobs = {
    police = { vehicles = { 'police', 'police2', 'police3', 'police4', 'police5', 'police6', 'polmav', 'sheriff', 'sheriff2' } },
    ambulance = { vehicles = { 'ambulance', 'firetruk' } },
    mechanic = { vehicles = { 'flatbed', 'towtruck', 'towtruck2', 'tooltruck' } }
}
